<?php require_once '../includes/auth.php'; require_role(['supplier','distributor']); $uid=(int)$_SESSION['user_id']; $role=$_SESSION['role']; $page_title=$role=='supplier'?'Transfer to Distributor':'Transfer to Shop';
if(isset($_POST['transfer'])){ $to=(int)$_POST['to_user_id']; $pid=(int)$_POST['product_id']; $fromw=(int)$_POST['from_warehouse_id']; $tow=(int)$_POST['to_warehouse_id']; $qty=(int)$_POST['qty'];
    $chk=mysqli_fetch_assoc(mysqli_query($conn,"SELECT quantity FROM stock WHERE owner_id=$uid AND product_id=$pid AND warehouse_id=$fromw"));
    if(!$chk || $chk['quantity']<$qty){ $error='Not enough stock available.'; }
    else{
        mysqli_query($conn,"UPDATE stock SET quantity=quantity-$qty WHERE owner_id=$uid AND product_id=$pid AND warehouse_id=$fromw");
        $toRole=$role=='supplier'?'distributor':'shop';
        mysqli_query($conn,"INSERT INTO stock(product_id,warehouse_id,owner_id,owner_role,quantity,reorder_level) VALUES($pid,$tow,$to,'$toRole',$qty,5) ON DUPLICATE KEY UPDATE quantity=quantity+$qty");
        mysqli_query($conn,"INSERT INTO stock_transfers(from_user_id,to_user_id,product_id,from_warehouse_id,to_warehouse_id,qty,status,note) VALUES($uid,$to,$pid,$fromw,$tow,$qty,'received','Auto completed')");
        notify_user($conn,$to,'Stock Received',"You received $qty items from {$_SESSION['name']}"); log_audit($conn,$uid,'Stock Transfer',"Product $pid Qty $qty To $to"); redirect('transfer.php');
    }
}
include '../includes/header.php'; include '../includes/sidebar.php';
$childRole=$role=='supplier'?'distributor':'shop'; $users=mysqli_query($conn,"SELECT * FROM users WHERE parent_id=$uid AND role='$childRole'"); $products=mysqli_query($conn,"SELECT p.* FROM products p INNER JOIN stock s ON s.product_id=p.id WHERE s.owner_id=$uid GROUP BY p.id"); $fromWh=mysqli_query($conn,"SELECT * FROM warehouses WHERE owner_id=$uid"); $toWh=mysqli_query($conn,"SELECT w.*,u.name owner FROM warehouses w JOIN users u ON u.id=w.owner_id WHERE u.parent_id=$uid AND u.role='$childRole'"); $history=mysqli_query($conn,"SELECT st.*,p.name product,u.name receiver FROM stock_transfers st JOIN products p ON p.id=st.product_id JOIN users u ON u.id=st.to_user_id WHERE st.from_user_id=$uid ORDER BY st.id DESC"); ?>
<div class="row g-4"><div class="col-md-4"><div class="card-box"><h5>Stock Transfer Automation</h5><?php if(isset($error)){ ?><div class="alert alert-danger"><?php echo $error; ?></div><?php } ?><form method="POST"><select class="form-select mb-2" name="to_user_id"><?php while($u=mysqli_fetch_assoc($users)){ ?><option value="<?php echo $u['id']; ?>"><?php echo $u['name']; ?></option><?php } ?></select><select class="form-select mb-2" name="product_id"><?php while($p=mysqli_fetch_assoc($products)){ ?><option value="<?php echo $p['id']; ?>"><?php echo $p['name']; ?></option><?php } ?></select><select class="form-select mb-2" name="from_warehouse_id"><?php while($w=mysqli_fetch_assoc($fromWh)){ ?><option value="<?php echo $w['id']; ?>"><?php echo $w['name']; ?></option><?php } ?></select><select class="form-select mb-2" name="to_warehouse_id"><?php while($w=mysqli_fetch_assoc($toWh)){ ?><option value="<?php echo $w['id']; ?>"><?php echo $w['name'].' - '.$w['owner']; ?></option><?php } ?></select><input class="form-control mb-3" type="number" name="qty" placeholder="Quantity"><button name="transfer" class="btn btn-success">Transfer Stock</button></form></div></div><div class="col-md-8"><div class="card-box"><h5>Transfer History</h5><table class="table"><tr><th>Product</th><th>Receiver</th><th>Qty</th><th>Status</th><th>Date</th></tr><?php while($h=mysqli_fetch_assoc($history)){ ?><tr><td><?php echo $h['product']; ?></td><td><?php echo $h['receiver']; ?></td><td><?php echo $h['qty']; ?></td><td><?php echo $h['status']; ?></td><td><?php echo $h['created_at']; ?></td></tr><?php } ?></table></div></div></div><?php include '../includes/footer.php'; ?>
